# Site settings
title: School of Data Switzerland
email: info@schoolofdata.ch
tagline: School of Data Schweiz will den Umgang mit und das Verständnis von Daten fördern.
description: > # this means to ignore newlines until "baseurl:"
  Wir bieten Unterstützung online über unser Forum und organisieren projektbasierte Workshops.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schoolofdata.ch" # the base hostname & protocol for your site
twitter: schoolofdata
facebook: schoolofdata
github: schoolofdata-swiss

# Build settings
markdown: kramdown
sass:
  sass_dir: sass
